image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-spring-boot-dashboard
    - angular.ng-template

tasks:
  - init: ./gradlew build
    command: ./gradlew bootRun

ports:
  - port: 8080
    onOpen: open-preview

